trinity:  # 修改trinity训练参数，如果使用verl则忽略该部分
  algorithm:
    algorithm_type: multi_step_grpo
    optimizer:
      lr: 1e-6
    repeat_times: 6
  buffer:
    batch_size: 8
    explorer_input:
      eval_tasksets: []
      taskset:
        default_workflow_type: astune_workflow
        format:
          prompt_key: question
          response_key: answer
        name: gsm8k
        path: http://localhost:8080
        rollout_args:
          temperature: 1.0
        split: train
        storage_type: astune
        subset_name: appworld
    total_epochs: 1000
    train_batch_size: 36
    trainer_input:
      experience_buffer:
        max_read_timeout: 18000
        name: agentscope_gsm8k_buffer
        storage_type: queue
  checkpoint_root_dir: ./trinity_checkpoints
  cluster:
    gpu_per_node: 8
    node_num: 1
  explorer:
    eval_interval: 999999
    max_repeat_times_per_runner: 1
    max_timeout: 7200
    rollout_model:
      dtype: bfloat16
      enable_auto_tool_choice: true
      enable_history: true
      enable_openai_api: true
      enable_prefix_caching: false
      enable_thinking: false
      enforce_eager: true
      engine_num: 2
      seed: 42
      tensor_parallel_size: 1
      tool_call_parser: hermes
    runner_per_model: 8
    # runner_state_report_interval: 30
  model:
    max_model_len: 21000
    max_response_tokens: 16000
  monitor:
    monitor_type: swanlab
    # monitor_type: tensorboard
  synchronizer:
    sync_interval: 2
    sync_method: nccl
    sync_style: dynamic_by_explorer
    sync_timeout: 1200
  trainer:
    grad_clip: 1.0
    max_token_len_per_gpu: 20000
    save_interval: 100
    ulysses_sequence_parallel_size: 1
    use_dynamic_bsz: true
