# Build and run the docker image with the following command:
#
# docker build -f scripts/docker/dockerfile -t ajet:latest .
# docker run -it --gpus all --shm-size="64g" --rm -v $PWD:/workspace -v <root_path_of_data_and_checkpoints>:/data ajet:latest

FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

WORKDIR /workspace

RUN chmod 1777 /tmp && apt update
RUN apt install -y \
    build-essential \
    curl git wget vim tmux net-tools \
    python3 python3-pip python3-dev python3-venv python3-packaging \
    libomp-dev infiniband-diags libibverbs-dev librdmacm-dev rdma-core perftest \
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && ln -sf /usr/bin/pip3 /usr/bin/pip

# For aliyun users, set pip source to aliyun mirror
# ENV PIP_INDEX_URL=http://mirrors.cloud.aliyuncs.com/pypi/simple/
# ENV PIP_TRUSTED_HOST=mirrors.cloud.aliyuncs.com

# set uv virtual environment path to a outside-of-workspace dir
ENV VIRTUAL_ENV=/opt/venv

# copy the AgentJets dir into the workspace (copy first to accelerate installation)
COPY scripts/docker/pyproject_for_docker_build.toml pyproject.toml

# Install uv
RUN pip install uv

# use uv to create a virtual environment and install dependencies
RUN uv venv /opt/venv --python=3.10

ENV UV_HTTP_TIMEOUT=9999

RUN . /opt/venv/bin/activate && uv pip install -e .[verl]
RUN . /opt/venv/bin/activate && uv pip install flash_attn==2.8.3 --no-deps --no-cache-dir --no-build-isolation


# cache friendly layer for code changes
COPY . .
RUN wget https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/astuner_archive/dataset.tar.gz
RUN mkdir -p /mnt/data_cpfs/model_cache/modelscope
RUN tar -xzf dataset.tar.gz -C /mnt/data_cpfs/model_cache/modelscope/ && rm dataset.tar.gz

# set entrypoint to activate the virtual environment
ENTRYPOINT ["/bin/bash", "-c", "source /opt/venv/bin/activate && exec \"$@\"", "--"]
CMD ["bash"]


# docker build -f scripts/docker/dockerfile -t ajet:latest .
# docker run -it --gpus all --shm-size="64g" --rm -v $PWD:/workspace -v <root_path_of_data_and_checkpoints>:/data ajet:latest
